-- Run in Supabase SQL editor for User Story 8 (stop-loss / take-profit)

alter table if exists trades
  add column if not exists exit_reason text;

comment on column trades.exit_reason is 'SELL only: MANUAL, STOP_LOSS, TAKE_PROFIT, LIMIT_FILL';

create table if not exists position_risk_rules (
  id bigint generated by default as identity primary key,
  user_id text not null,
  symbol text not null,
  status text not null default 'ACTIVE',
  entry_price numeric not null,
  stop_loss_price numeric,
  take_profit_price numeric,
  stop_loss_pct numeric,
  take_profit_pct numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  triggered_at timestamptz,
  trigger_type text
);

create index if not exists idx_position_risk_rules_active
  on position_risk_rules (user_id, symbol)
  where status = 'ACTIVE';

create unique index if not exists idx_position_risk_rules_one_active
  on position_risk_rules (user_id, symbol)
  where status = 'ACTIVE';
